### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by ChristianKleineidam** [skydoves/PreferenceRoom#17]
Currently, there's no sample project which makes it hard to understand how to use the library. It would be great to have a small sample project. Especially one in kotlin.

**Comment by skydoves** [comment]
@ChristianKleineidam 
Here are some demo & sample project which used PreferenceRoom.
[demo-kotlin](https://github.com/skydoves/PreferenceRoom/tree/master/demo-kotlin), [GithubFollows](https://github.com/skydoves/githubfollows), [All-in-One](https://github.com/skydoves/All-In-One).

**Comment by ChristianKleineidam** [comment]
It's not a real sample project as it only builds when it's in the same dictionary (it's gradle values depend on being colocated).

**Comment by skydoves** [comment]
@ChristianKleineidam 
In kotlin project, you should add below dependencies on build.gradle(app) module.
```gradle
implementation "com.github.skydoves:preferenceroom:1.1.8"
kapt"com.github.skydoves:preferenceroom-processor:1.1.8"
```
And here is [sample project](https://github.com/skydoves/All-In-One/blob/master/app/build.gradle) how to add the dependency to your kotlin project. (line 76~78).
