### ISSUE TITLE
Annotation processor is not incremental

### ISSUE THREAD

**Issue by sambit-m** [skydoves/PreferenceRoom#19]
**Please complete the following information:**
- Library Version [v1.1.8]
- Affected Device(s) [Samsung Galaxy s7 with Android 8.0]
 
**Describe the Bug:**

Annotation processor is not incremental

Gradle(app): 
dependencies {
.....
def preference_room = "1.1.8"
implementation "com.github.skydoves:preferenceroom:$preference_room"
kapt "com.github.skydoves:preferenceroom-processor:$preference_room"
.....
}

Gradle warning: 
w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: com.skydoves.processor.PreferenceRoomProcessor (NON_INCREMENTAL), com.google.auto.service.processor.AutoServiceProcessor (NON_INCREMENTAL).

**Expected Behavior:**
Annotation processor has to be incremental.

**Comment by skydoves** [comment]
@sambit-m 
Hi, thank you for your issue!
It is resolved in version `1.1.9`.
Please check the new updated version. :)
