### ISSUE TITLE
How to create an entry in preference room, with default value

### ISSUE THREAD

**Issue by Dalakoti07** [skydoves/PreferenceRoom#24]
- Library Version 1.2.1
- Affected Device(s) Any
 
**Describe the Bug:**
How to create entry in room preference component with some default value, as of I am doing it like below

`@PreferenceEntity("OnBoardingData")
   open class OnBoardingData { @KeyName("fake")
    @JvmField
    val fakeBoolean = true
}`

Here I have to make sure that annotation name and variable name are different like "fake" and fakeBoolean, now I check if preference entry is null then get default value, something like this 

`if(onBoardingComponent.OnBoardingData.cntainsFake()){
        ..........
}else{
    // use default value like 
     onBoardingComponent.OnBoardingData.fakeBoolean
}
`

**Expected Behavior:**
Is their not a way to add this default value into the prefs, rather than making an extra check while consuming it

**Comment by skydoves** [comment]
Hi, you should use `fake` property instead of the `fakeBoolean` method.
Because  `OnBoardingData` class will be generated on the compile-time, and `getFake` method will be generated like the below.

```kotlin

component.OnBoardingData().fake // default value is true.

@Nullable
  public boolean getFake() {
    return preference.getBoolean("fake", true);
  }
```

**Comment by Dalakoti07** [comment]
Thank you for prompt reply, but how to achieve this when field is custom object something like car, in that case generated code has something like this

`@Nullable
  public AgeGroup[] getAgesBrackets() {
    AgeGroupListConverter value = new AgeGroupListConverter(com.niyotail.core.data.model.entities.AgeGroup[].class);
    return (AgeGroup[])value.convertType(
        preference.getString("agesBrackets", null));
  }`
  
  I want default array arraylist rather than null

**Comment by skydoves** [comment]
For the custom object, there is no way to set a default value now.

**Comment by Dalakoti07** [comment]
Okay, thanks.

Are you planning to add this in coming versions?

**Comment by skydoves** [comment]
Not in the recent schedule, but I will consider it.
Thanks for your report!

**Comment by Dalakoti07** [comment]
Thanks
