### ISSUE TITLE
Any way of encrypting the whole Entity?

### ISSUE THREAD

**Issue by marconealberto** [skydoves/PreferenceRoom#9]
I have a class like this:

```
@PreferenceEntity(name = "MyPreferences")
public class MyPreferences {

	@TypeConverter(converter = BaseGsonConverter.class)
	protected Index MyClass;

}
```

I need to encrypt MyClass. How can I do that?

**Comment by skydoves** [comment]
@marconealberto 
It's implemented encrypt & decrypt automatically using @EncryptEntity annotation at version `1.1.6`.
You can reference [demo-project](https://github.com/skydoves/PreferenceRoom/blob/master/demo/src/main/java/com/skydoves/preferenceroomdemo/entities/Profile.java). Thank you!
